auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Vaellys.com
url: http://Vaellys.com
feed: /atom.xml
author_info: <a href="http://vaellys.github.com/">Vaellys</a>
